/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MembershipsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_list"];
        put?: never;
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_findOne"];
        put?: never;
        post?: never;
        delete: operations["UsersController_remove"];
        options?: never;
        head?: never;
        patch: operations["UsersController_update"];
        trace?: never;
    };
    "/api/users/{id}/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UsersController_resendInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LocationsController_list"];
        put?: never;
        post: operations["LocationsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LocationsController_findOne"];
        put?: never;
        post?: never;
        delete: operations["LocationsController_remove"];
        options?: never;
        head?: never;
        patch: operations["LocationsController_update"];
        trace?: never;
    };
    "/api/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClassesController_list"];
        put?: never;
        post: operations["ClassesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClassesController_findOne"];
        put?: never;
        post?: never;
        delete: operations["ClassesController_remove"];
        options?: never;
        head?: never;
        patch: operations["ClassesController_update"];
        trace?: never;
    };
    "/api/trainees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TraineesController_list"];
        put?: never;
        post: operations["TraineesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TraineesController_findOne"];
        put?: never;
        post?: never;
        delete: operations["TraineesController_remove"];
        options?: never;
        head?: never;
        patch: operations["TraineesController_update"];
        trace?: never;
    };
    "/api/trainees/{traineeId}/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ContactsController_list"];
        put?: never;
        post: operations["ContactsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainees/{traineeId}/contacts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["ContactsController_remove"];
        options?: never;
        head?: never;
        patch: operations["ContactsController_update"];
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SessionsController_list"];
        put?: never;
        post: operations["SessionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SessionsController_findOne"];
        put?: never;
        post?: never;
        delete: operations["SessionsController_remove"];
        options?: never;
        head?: never;
        patch: operations["SessionsController_update"];
        trace?: never;
    };
    "/api/class-schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClassSchedulesController_list"];
        put?: never;
        post: operations["ClassSchedulesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/class-schedules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClassSchedulesController_findOne"];
        put?: never;
        post?: never;
        delete: operations["ClassSchedulesController_remove"];
        options?: never;
        head?: never;
        patch: operations["ClassSchedulesController_update"];
        trace?: never;
    };
    "/api/class-schedules/generate-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ClassSchedulesController_generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/attendance-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AttendancesController_candidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/attendances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AttendancesController_list"];
        put: operations["AttendancesController_bulkMark"];
        post: operations["AttendancesController_addTrainee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/rsvp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AttendancesController_rsvp"];
        trace?: never;
    };
    "/api/me/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AttendancesController_myUpcoming"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FeesController_list"];
        put?: never;
        post: operations["FeesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fees/unbilled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FeesController_unbilled"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FeesController_findOne"];
        put?: never;
        post?: never;
        delete: operations["FeesController_remove"];
        options?: never;
        head?: never;
        patch: operations["FeesController_update"];
        trace?: never;
    };
    "/api/fees/generate-monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FeesController_generateMonthly"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fees/generate-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FeesController_generateSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/fees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CustomerFeesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fees/{feeId}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaymentsController_list"];
        put?: never;
        post: operations["PaymentsController_record"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fees/{feeId}/payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["PaymentsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/fees-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DashboardController_feesSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/cashflow-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DashboardController_cashflowSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TenantsController_list"];
        put?: never;
        post: operations["TenantsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        RefreshDto: {
            refreshToken?: string;
        };
        ForgotPasswordDto: {
            /** Format: email */
            email: string;
        };
        ResetPasswordDto: {
            token: string;
            newPassword: string;
        };
        CreateUserDto: {
            /** Format: email */
            email: string;
            firstName?: string;
            lastName?: string;
            phone?: string;
            /** @enum {string} */
            role: "SUPER_ADMIN" | "ADMIN" | "EMPLOYEE" | "CUSTOMER";
            locationIds?: string[];
        };
        UpdateUserDto: {
            firstName?: string | null;
            lastName?: string | null;
            phone?: string | null;
            isActive?: boolean;
            password?: string;
            /** @enum {string} */
            role?: "SUPER_ADMIN" | "ADMIN" | "EMPLOYEE" | "CUSTOMER";
            locationIds?: string[];
        };
        CreateLocationDto: {
            name: string;
            address?: string;
        };
        UpdateLocationDto: {
            name?: string;
            address?: string;
            isActive?: boolean;
        };
        CreateClassDto: {
            name: string;
            description?: string;
            /** @enum {string} */
            billingMode: "PER_MONTH" | "PER_SESSION";
            monthlyAmount?: number;
            sessionPrice?: number;
            locationIds?: string[];
            trainerIds?: string[];
            traineeIds?: string[];
        };
        UpdateClassDto: {
            name?: string;
            description?: string;
            monthlyAmount?: number;
            sessionPrice?: number;
            isActive?: boolean;
            locationIds?: string[];
            trainerIds?: string[];
            traineeIds?: string[];
        };
        CreateContactDto: {
            firstName: string;
            lastName: string;
            /** @enum {string} */
            relationship: "PARENT" | "GUARDIAN" | "GRANDPARENT" | "SIBLING" | "OTHER";
            phone?: string;
            /** Format: email */
            email?: string;
            isPrimary?: boolean;
        };
        CreateTraineeDto: {
            firstName: string;
            lastName: string;
            dateOfBirth: string;
            phone?: string;
            /** Format: email */
            email?: string;
            notes?: string;
            userId?: string;
            guardianUserIds?: string[];
            locationIds?: string[];
            classIds?: string[];
            contacts?: components["schemas"]["CreateContactDto"][];
        };
        UpdateTraineeDto: {
            firstName?: string;
            lastName?: string;
            dateOfBirth?: string;
            phone?: string;
            /** Format: email */
            email?: string;
            notes?: string;
            isActive?: boolean;
            userId?: string | null;
            guardianUserIds?: string[];
            locationIds?: string[];
            classIds?: string[];
        };
        UpdateContactDto: {
            firstName?: string;
            lastName?: string;
            /** @enum {string} */
            relationship?: "PARENT" | "GUARDIAN" | "GRANDPARENT" | "SIBLING" | "OTHER";
            phone?: string;
            /** Format: email */
            email?: string;
            isPrimary?: boolean;
        };
        CreateSessionDto: {
            classId: string;
            locationId: string;
            startsAt: string;
            endsAt: string;
            notes?: string;
            trainerIds?: string[];
        };
        UpdateSessionDto: {
            locationId?: string;
            startsAt?: string;
            endsAt?: string;
            /** @enum {string} */
            status?: "SCHEDULED" | "COMPLETED" | "CANCELLED";
            notes?: string;
            trainerIds?: string[];
        };
        CreateClassScheduleDto: {
            classId: string;
            locationId: string;
            /** @enum {string} */
            dayOfWeek: "MON" | "TUE" | "WED" | "THU" | "FRI" | "SAT" | "SUN";
            startTime: string;
            endTime: string;
            isActive?: boolean;
        };
        UpdateClassScheduleDto: {
            locationId?: string;
            /** @enum {string} */
            dayOfWeek?: "MON" | "TUE" | "WED" | "THU" | "FRI" | "SAT" | "SUN";
            startTime?: string;
            endTime?: string;
            isActive?: boolean;
        };
        GenerateSessionsDto: {
            from: string;
            to: string;
            classId?: string;
        };
        AddAttendanceDto: {
            traineeId: string;
        };
        BulkMarkAttendanceItemDto: {
            traineeId: string;
            /** @enum {string} */
            status: "PENDING" | "PRESENT" | "ABSENT" | "EXCUSED";
            notes?: string;
        };
        BulkMarkAttendancesDto: {
            items: components["schemas"]["BulkMarkAttendanceItemDto"][];
        };
        RsvpDto: {
            traineeId: string;
            /** @enum {string} */
            traineeRsvp: "CONFIRMED" | "DECLINED" | "RESCHEDULE_REQUESTED";
        };
        CreateFeeDto: {
            classId: string;
            traineeId: string;
            periodStart: string;
            periodEnd: string;
            amount: number;
            notes?: string;
        };
        UpdateFeeDto: {
            amount?: number;
            periodStart?: string;
            periodEnd?: string;
            notes?: string;
        };
        GenerateMonthlyFeesDto: {
            periodStart: string;
            periodEnd: string;
            classId?: string;
        };
        GenerateSessionFeesDto: {
            from: string;
            to: string;
            classId?: string;
        };
        CreatePaymentDto: {
            amount: number;
            paidAt: string;
            method?: string;
            notes?: string;
        };
        CreateTenantDto: {
            name: string;
            slug: string;
            locationName: string;
            locationAddress?: string;
            /** Format: email */
            adminEmail: string;
            adminFirstName?: string;
            adminLastName?: string;
        };
        Health: {
            /** @constant */
            status: "ok";
            service: string;
            timestamp: string;
        };
        LoginResponse: {
            accessToken: string;
            memberships: {
                tenantId: string;
                tenantName: string;
                /** @enum {string} */
                role: "SUPER_ADMIN" | "ADMIN" | "EMPLOYEE" | "CUSTOMER";
            }[];
        };
        RefreshResponse: {
            accessToken: string;
            refreshToken: string;
        } | {
            accessToken: string;
        };
        ForgotPasswordResponse: {
            message: string;
        };
        LoginMembershipList: {
            tenantId: string;
            tenantName: string;
            /** @enum {string} */
            role: "SUPER_ADMIN" | "ADMIN" | "EMPLOYEE" | "CUSTOMER";
        }[];
        PaginatedUserSummary: {
            items: {
                id: string;
                email: string;
                firstName: string | null;
                lastName: string | null;
                phone: string | null;
                /** @enum {string} */
                role: "SUPER_ADMIN" | "ADMIN" | "EMPLOYEE" | "CUSTOMER";
                tenantId: string | null;
                isActive: boolean;
                /** @enum {string} */
                status: "PENDING" | "ACTIVE" | "INACTIVE";
                locations: {
                    id: string;
                    name: string;
                }[];
                createdAt: string;
                updatedAt: string;
            }[];
            page: number;
            pageSize: number;
            total: number;
            totalPages: number;
        };
        CreatedUser: {
            id: string;
            email: string;
            firstName: string | null;
            lastName: string | null;
            phone: string | null;
            /** @enum {string} */
            role: "SUPER_ADMIN" | "ADMIN" | "EMPLOYEE" | "CUSTOMER";
            tenantId: string | null;
            isActive: boolean;
            /** @enum {string} */
            status: "PENDING" | "ACTIVE" | "INACTIVE";
            locations: {
                id: string;
                name: string;
            }[];
            createdAt: string;
            updatedAt: string;
            notificationSent: boolean;
            attachedExisting?: boolean;
        };
        UserSummary: {
            id: string;
            email: string;
            firstName: string | null;
            lastName: string | null;
            phone: string | null;
            /** @enum {string} */
            role: "SUPER_ADMIN" | "ADMIN" | "EMPLOYEE" | "CUSTOMER";
            tenantId: string | null;
            isActive: boolean;
            /** @enum {string} */
            status: "PENDING" | "ACTIVE" | "INACTIVE";
            locations: {
                id: string;
                name: string;
            }[];
            createdAt: string;
            updatedAt: string;
        };
        InviteResult: {
            inviteEmailSent: boolean;
        };
        PaginatedLocation: {
            items: {
                id: string;
                tenantId: string;
                name: string;
                address: string | null;
                isActive: boolean;
                createdAt: string;
                updatedAt: string;
            }[];
            page: number;
            pageSize: number;
            total: number;
            totalPages: number;
        };
        Location: {
            id: string;
            tenantId: string;
            name: string;
            address: string | null;
            isActive: boolean;
            createdAt: string;
            updatedAt: string;
        };
        PaginatedClassRow: {
            items: {
                id: string;
                tenantId: string;
                name: string;
                description: string | null;
                /** @enum {string} */
                billingMode: "PER_MONTH" | "PER_SESSION";
                monthlyAmount: null | string;
                sessionPrice: null | string;
                isActive: boolean;
                createdAt: string;
                updatedAt: string;
            }[];
            page: number;
            pageSize: number;
            total: number;
            totalPages: number;
        };
        ClassRow: {
            id: string;
            tenantId: string;
            name: string;
            description: string | null;
            /** @enum {string} */
            billingMode: "PER_MONTH" | "PER_SESSION";
            monthlyAmount: null | string;
            sessionPrice: null | string;
            isActive: boolean;
            createdAt: string;
            updatedAt: string;
        };
        ClassDetail: {
            id: string;
            tenantId: string;
            name: string;
            description: string | null;
            /** @enum {string} */
            billingMode: "PER_MONTH" | "PER_SESSION";
            monthlyAmount: null | string;
            sessionPrice: null | string;
            isActive: boolean;
            createdAt: string;
            updatedAt: string;
            locations: {
                id: string;
                name: string;
            }[];
            trainers: {
                id: string;
                firstName: string | null;
                lastName: string | null;
                email: string;
            }[];
            trainees: {
                id: string;
                firstName: string;
                lastName: string;
            }[];
        };
        PaginatedTrainee: {
            items: {
                id: string;
                tenantId: string;
                firstName: string;
                lastName: string;
                dateOfBirth: string;
                phone: string | null;
                email: string | null;
                notes: string | null;
                isActive: boolean;
                userId: string | null;
                createdAt: string;
                updatedAt: string;
            }[];
            page: number;
            pageSize: number;
            total: number;
            totalPages: number;
        };
        Trainee: {
            id: string;
            tenantId: string;
            firstName: string;
            lastName: string;
            dateOfBirth: string;
            phone: string | null;
            email: string | null;
            notes: string | null;
            isActive: boolean;
            userId: string | null;
            createdAt: string;
            updatedAt: string;
        };
        TraineeDetail: {
            id: string;
            tenantId: string;
            firstName: string;
            lastName: string;
            dateOfBirth: string;
            phone: string | null;
            email: string | null;
            notes: string | null;
            isActive: boolean;
            userId: string | null;
            createdAt: string;
            updatedAt: string;
            contacts: {
                id: string;
                tenantId: string;
                traineeId: string;
                firstName: string;
                lastName: string;
                /** @enum {string} */
                relationship: "PARENT" | "GUARDIAN" | "GRANDPARENT" | "SIBLING" | "OTHER";
                phone: string | null;
                email: string | null;
                isPrimary: boolean;
                createdAt: string;
                updatedAt: string;
            }[];
            locations: {
                id: string;
                tenantId: string;
                name: string;
                address: string | null;
                isActive: boolean;
                createdAt: string;
                updatedAt: string;
            }[];
            classes: {
                id: string;
                tenantId: string;
                name: string;
                description: string | null;
                /** @enum {string} */
                billingMode: "PER_MONTH" | "PER_SESSION";
                monthlyAmount: null | string;
                sessionPrice: null | string;
                isActive: boolean;
                createdAt: string;
                updatedAt: string;
            }[];
            guardians: {
                id: string;
                firstName: string | null;
                lastName: string | null;
                email: string;
            }[];
            user: {
                id: string;
                email: string;
            } | null;
        };
        ContactPersonList: {
            id: string;
            tenantId: string;
            traineeId: string;
            firstName: string;
            lastName: string;
            /** @enum {string} */
            relationship: "PARENT" | "GUARDIAN" | "GRANDPARENT" | "SIBLING" | "OTHER";
            phone: string | null;
            email: string | null;
            isPrimary: boolean;
            createdAt: string;
            updatedAt: string;
        }[];
        ContactPerson: {
            id: string;
            tenantId: string;
            traineeId: string;
            firstName: string;
            lastName: string;
            /** @enum {string} */
            relationship: "PARENT" | "GUARDIAN" | "GRANDPARENT" | "SIBLING" | "OTHER";
            phone: string | null;
            email: string | null;
            isPrimary: boolean;
            createdAt: string;
            updatedAt: string;
        };
        PaginatedSession: {
            items: {
                id: string;
                tenantId: string;
                classId: string;
                locationId: string;
                startsAt: string;
                endsAt: string;
                /** @enum {string} */
                status: "SCHEDULED" | "COMPLETED" | "CANCELLED";
                notes: string | null;
                createdAt: string;
                updatedAt: string;
            }[];
            page: number;
            pageSize: number;
            total: number;
            totalPages: number;
        };
        Session: {
            id: string;
            tenantId: string;
            classId: string;
            locationId: string;
            startsAt: string;
            endsAt: string;
            /** @enum {string} */
            status: "SCHEDULED" | "COMPLETED" | "CANCELLED";
            notes: string | null;
            createdAt: string;
            updatedAt: string;
        };
        SessionDetail: {
            id: string;
            tenantId: string;
            classId: string;
            locationId: string;
            startsAt: string;
            endsAt: string;
            /** @enum {string} */
            status: "SCHEDULED" | "COMPLETED" | "CANCELLED";
            notes: string | null;
            createdAt: string;
            updatedAt: string;
            class: {
                id: string;
                name: string;
                /** @enum {string} */
                billingMode: "PER_MONTH" | "PER_SESSION";
            };
            location: {
                id: string;
                name: string;
            };
            trainers: {
                id: string;
                firstName: string | null;
                lastName: string | null;
                email: string;
            }[];
        };
        PaginatedClassSchedule: {
            items: {
                id: string;
                tenantId: string;
                classId: string;
                locationId: string;
                /** @enum {string} */
                dayOfWeek: "MON" | "TUE" | "WED" | "THU" | "FRI" | "SAT" | "SUN";
                startTime: string;
                endTime: string;
                isActive: boolean;
                createdAt: string;
                updatedAt: string;
            }[];
            page: number;
            pageSize: number;
            total: number;
            totalPages: number;
        };
        ClassSchedule: {
            id: string;
            tenantId: string;
            classId: string;
            locationId: string;
            /** @enum {string} */
            dayOfWeek: "MON" | "TUE" | "WED" | "THU" | "FRI" | "SAT" | "SUN";
            startTime: string;
            endTime: string;
            isActive: boolean;
            createdAt: string;
            updatedAt: string;
        };
        GenerateResult: {
            created: number;
            skipped: number;
        };
        AttendanceWithTraineeList: {
            id: string;
            tenantId: string;
            sessionId: string;
            traineeId: string;
            /** @enum {string} */
            status: "PENDING" | "PRESENT" | "ABSENT" | "EXCUSED";
            traineeRsvp: ("CONFIRMED" | "DECLINED" | "RESCHEDULE_REQUESTED") | null;
            notes: string | null;
            markedAt: null | string;
            markedById: string | null;
            markedByEmailSnapshot: string | null;
            markedByNameSnapshot: string | null;
            createdAt: string;
            updatedAt: string;
            trainee: {
                id: string;
                firstName: string;
                lastName: string;
            };
        }[];
        Attendance: {
            id: string;
            tenantId: string;
            sessionId: string;
            traineeId: string;
            /** @enum {string} */
            status: "PENDING" | "PRESENT" | "ABSENT" | "EXCUSED";
            traineeRsvp: ("CONFIRMED" | "DECLINED" | "RESCHEDULE_REQUESTED") | null;
            notes: string | null;
            markedAt: null | string;
            markedById: string | null;
            markedByEmailSnapshot: string | null;
            markedByNameSnapshot: string | null;
            createdAt: string;
            updatedAt: string;
        };
        BulkMarkResult: {
            updated: number;
        };
        CustomerSessionEntryList: {
            id: string;
            tenantId: string;
            classId: string;
            locationId: string;
            startsAt: string;
            endsAt: string;
            /** @enum {string} */
            status: "SCHEDULED" | "COMPLETED" | "CANCELLED";
            notes: string | null;
            createdAt: string;
            updatedAt: string;
            class: {
                id: string;
                name: string;
            };
            location: {
                id: string;
                name: string;
            };
            attendances: {
                id: string;
                tenantId: string;
                sessionId: string;
                traineeId: string;
                /** @enum {string} */
                status: "PENDING" | "PRESENT" | "ABSENT" | "EXCUSED";
                traineeRsvp: ("CONFIRMED" | "DECLINED" | "RESCHEDULE_REQUESTED") | null;
                notes: string | null;
                markedAt: null | string;
                markedById: string | null;
                markedByEmailSnapshot: string | null;
                markedByNameSnapshot: string | null;
                createdAt: string;
                updatedAt: string;
                trainee: {
                    id: string;
                    firstName: string;
                    lastName: string;
                };
            }[];
        }[];
        PaginatedFeeRow: {
            items: {
                id: string;
                tenantId: string;
                classId: string;
                traineeId: string;
                sessionId: string | null;
                periodStart: string;
                periodEnd: string;
                amount: string;
                /** @enum {string} */
                status: "UNPAID" | "PARTIAL" | "PAID";
                notes: string | null;
                createdAt: string;
                updatedAt: string;
                paid: string;
            }[];
            page: number;
            pageSize: number;
            total: number;
            totalPages: number;
        };
        Fee: {
            id: string;
            tenantId: string;
            classId: string;
            traineeId: string;
            sessionId: string | null;
            periodStart: string;
            periodEnd: string;
            amount: string;
            /** @enum {string} */
            status: "UNPAID" | "PARTIAL" | "PAID";
            notes: string | null;
            createdAt: string;
            updatedAt: string;
        };
        UnbilledFeeList: {
            classId: string;
            className: string;
            traineeId: string;
            traineeFirstName: string;
            traineeLastName: string;
            amount: string;
        }[];
        FeeDetail: {
            id: string;
            tenantId: string;
            classId: string;
            traineeId: string;
            sessionId: string | null;
            periodStart: string;
            periodEnd: string;
            amount: string;
            /** @enum {string} */
            status: "UNPAID" | "PARTIAL" | "PAID";
            notes: string | null;
            createdAt: string;
            updatedAt: string;
            class: {
                id: string;
                name: string;
                /** @enum {string} */
                billingMode: "PER_MONTH" | "PER_SESSION";
            };
            trainee: {
                id: string;
                firstName: string;
                lastName: string;
            };
            payments: {
                id: string;
                tenantId: string;
                feeId: string;
                amount: string;
                paidAt: string;
                method: string | null;
                notes: string | null;
                recordedById: string | null;
                recordedByEmailSnapshot: string | null;
                recordedByNameSnapshot: string | null;
                createdAt: string;
            }[];
        };
        CustomerFeeEntryList: {
            id: string;
            tenantId: string;
            classId: string;
            traineeId: string;
            sessionId: string | null;
            periodStart: string;
            periodEnd: string;
            amount: string;
            /** @enum {string} */
            status: "UNPAID" | "PARTIAL" | "PAID";
            notes: string | null;
            createdAt: string;
            updatedAt: string;
            class: {
                id: string;
                name: string;
            };
            trainee: {
                id: string;
                firstName: string;
                lastName: string;
            };
            payments: {
                id: string;
                tenantId: string;
                feeId: string;
                amount: string;
                paidAt: string;
                method: string | null;
                notes: string | null;
                recordedById: string | null;
                recordedByEmailSnapshot: string | null;
                recordedByNameSnapshot: string | null;
                createdAt: string;
            }[];
        }[];
        PaymentList: {
            id: string;
            tenantId: string;
            feeId: string;
            amount: string;
            paidAt: string;
            method: string | null;
            notes: string | null;
            recordedById: string | null;
            recordedByEmailSnapshot: string | null;
            recordedByNameSnapshot: string | null;
            createdAt: string;
        }[];
        Payment: {
            id: string;
            tenantId: string;
            feeId: string;
            amount: string;
            paidAt: string;
            method: string | null;
            notes: string | null;
            recordedById: string | null;
            recordedByEmailSnapshot: string | null;
            recordedByNameSnapshot: string | null;
            createdAt: string;
        };
        FeesSummaryEntryList: {
            period: string;
            collected: number;
            pending: number;
        }[];
        CashflowSummaryEntryList: {
            period: string;
            collected: number;
            billed: number;
        }[];
        TenantSummaryList: {
            id: string;
            slug: string;
            name: string;
            isActive: boolean;
        }[];
        CreatedTenant: {
            id: string;
            slug: string;
            name: string;
            isActive: boolean;
            notificationSent: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_forgotPassword: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForgotPasswordResponse"];
                };
            };
        };
    };
    AuthController_resetPassword: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MembershipsController_list: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginMembershipList"];
                };
            };
        };
    };
    UsersController_list: {
        parameters: {
            query?: {
                role?: "SUPER_ADMIN" | "ADMIN" | "EMPLOYEE" | "CUSTOMER";
                search?: string;
                page?: number;
                pageSize?: number;
            };
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUserSummary"];
                };
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedUser"];
                };
            };
        };
    };
    UsersController_findOne: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"];
                };
            };
        };
    };
    UsersController_remove: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_update: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"];
                };
            };
        };
    };
    UsersController_resendInvite: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteResult"];
                };
            };
        };
    };
    LocationsController_list: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLocation"];
                };
            };
        };
    };
    LocationsController_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLocationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
        };
    };
    LocationsController_findOne: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
        };
    };
    LocationsController_remove: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LocationsController_update: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLocationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
        };
    };
    ClassesController_list: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                isActive?: boolean;
                search?: string;
            };
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedClassRow"];
                };
            };
        };
    };
    ClassesController_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClassDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassRow"];
                };
            };
        };
    };
    ClassesController_findOne: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassDetail"];
                };
            };
        };
    };
    ClassesController_remove: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClassesController_update: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClassDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassRow"];
                };
            };
        };
    };
    TraineesController_list: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                search?: string;
            };
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTrainee"];
                };
            };
        };
    };
    TraineesController_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTraineeDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trainee"];
                };
            };
        };
    };
    TraineesController_findOne: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraineeDetail"];
                };
            };
        };
    };
    TraineesController_remove: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TraineesController_update: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTraineeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trainee"];
                };
            };
        };
    };
    ContactsController_list: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                traineeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactPersonList"];
                };
            };
        };
    };
    ContactsController_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                traineeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContactDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactPerson"];
                };
            };
        };
    };
    ContactsController_remove: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                traineeId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContactsController_update: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                traineeId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateContactDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactPerson"];
                };
            };
        };
    };
    SessionsController_list: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                startsAtFrom?: string;
                startsAtBefore?: string;
            };
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSession"];
                };
            };
        };
    };
    SessionsController_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    SessionsController_findOne: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
        };
    };
    SessionsController_remove: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SessionsController_update: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSessionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    ClassSchedulesController_list: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedClassSchedule"];
                };
            };
        };
    };
    ClassSchedulesController_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClassScheduleDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassSchedule"];
                };
            };
        };
    };
    ClassSchedulesController_findOne: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassSchedule"];
                };
            };
        };
    };
    ClassSchedulesController_remove: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClassSchedulesController_update: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClassScheduleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassSchedule"];
                };
            };
        };
    };
    ClassSchedulesController_generate: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateSessionsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResult"];
                };
            };
        };
    };
    AttendancesController_candidates: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTrainee"];
                };
            };
        };
    };
    AttendancesController_list: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceWithTraineeList"];
                };
            };
        };
    };
    AttendancesController_bulkMark: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkMarkAttendancesDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkMarkResult"];
                };
            };
        };
    };
    AttendancesController_addTrainee: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddAttendanceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attendance"];
                };
            };
        };
    };
    AttendancesController_rsvp: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RsvpDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attendance"];
                };
            };
        };
    };
    AttendancesController_myUpcoming: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerSessionEntryList"];
                };
            };
        };
    };
    FeesController_list: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                status?: "UNPAID" | "PARTIAL" | "PAID" | "OUTSTANDING";
                classId?: string;
                traineeId?: string;
                periodStartFrom?: string;
                periodStartTo?: string;
            };
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedFeeRow"];
                };
            };
        };
    };
    FeesController_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFeeDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fee"];
                };
            };
        };
    };
    FeesController_unbilled: {
        parameters: {
            query: {
                periodStart: string;
                periodEnd: string;
                classId?: string;
            };
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnbilledFeeList"];
                };
            };
        };
    };
    FeesController_findOne: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeeDetail"];
                };
            };
        };
    };
    FeesController_remove: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FeesController_update: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFeeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fee"];
                };
            };
        };
    };
    FeesController_generateMonthly: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateMonthlyFeesDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResult"];
                };
            };
        };
    };
    FeesController_generateSession: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateSessionFeesDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResult"];
                };
            };
        };
    };
    CustomerFeesController_list: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerFeeEntryList"];
                };
            };
        };
    };
    PaymentsController_list: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                feeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentList"];
                };
            };
        };
    };
    PaymentsController_record: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                feeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePaymentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
        };
    };
    PaymentsController_remove: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path: {
                feeId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_feesSummary: {
        parameters: {
            query?: {
                /** @description Inclusive start (YYYY-MM-DD), rounded down to its month. Omitted: 5 months before "to". */
                from?: string;
                /** @description Inclusive end (YYYY-MM-DD), rounded up to its month. Omitted: the current month, or "from" own month when "from" is in the future. A span over 120 months is rejected with 400. */
                to?: string;
            };
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeesSummaryEntryList"];
                };
            };
        };
    };
    DashboardController_cashflowSummary: {
        parameters: {
            query?: {
                /** @description Inclusive start (YYYY-MM-DD), rounded down to its month. Omitted: 5 months before "to". */
                from?: string;
                /** @description Inclusive end (YYYY-MM-DD), rounded up to its month. Omitted: the current month, or "from" own month when "from" is in the future. A span over 120 months is rejected with 400. */
                to?: string;
            };
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashflowSummaryEntryList"];
                };
            };
        };
    };
    TenantsController_list: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSummaryList"];
                };
            };
        };
    };
    TenantsController_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant the caller acts in. A tenant-bound user must name one of their own tenants (403 otherwise); a SUPER_ADMIN may name any active tenant (404 otherwise). */
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTenantDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedTenant"];
                };
            };
        };
    };
}
